enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - darwin
    - linux
    - windows

yarnPath: .yarn/releases/yarn-4.9.1.cjs
