name: "Action Plan (matrix)"
description: "Generate Github Actions matrix."
inputs:
  plan-file:
    description: The TypeScript file to load and run for plan generation.
    required: true
  plan:
    description: The name of the plan to generate.
    required: false
    default: default
  tsconfig:
    description: The custom TypeScript config.
    required: false
outputs:
  matrix:
    description: "The generated matrix."
    value: ${{ steps.execution.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - run: node "$ACTION_PATH/build/loader/index.js"
      shell: bash
      id: execution
      env:
        ACTION_PATH: ${{ github.action_path }}
        INPUT_PLAN_FILE: ${{ inputs.plan-file }}
        INPUT_PLAN: ${{ inputs.plan }}
        INPUT_TSCONFIG: ${{ inputs.tsconfig }}
