name: "Action Plan (matrix)"
description: "Generate Github Actions matrix."
inputs:
  plan-file:
    description: The TypeScript file to load and run for plan generation.
    required: true
  plan:
    description: The name of the plan to generate.
    required: false
    default: default
  tsconfig:
    description: The custom TypeScript config.
    required: false
outputs:
  matrix:
    description: "The generated matrix."
runs:
  using: "node16"
  main: "build/loader/index.js"
